// CoaXPress register map.  Generated by src/regmap/gen_regmap.py from src/regmap/cxp_regmap.yaml -- do not edit.
#pragma once

#include <cstdint>

namespace cxp::reg {

// ---- Bootstrap registers (§10.3, Table 45) ----
inline constexpr uint32_t STANDARD = 0x0000;
inline constexpr uint32_t REVISION = 0x0004;
inline constexpr uint32_t XML_MANIFEST_SIZE = 0x0008;
inline constexpr uint32_t XML_MANIFEST_SELECTOR = 0x000C;
inline constexpr uint32_t XML_VERSION = 0x0010;
inline constexpr uint32_t XML_SCHEMA_VERSION = 0x0014;
inline constexpr uint32_t XML_URL_ADDRESS = 0x0018;
inline constexpr uint32_t IIDC2_ADDRESS = 0x001C;
inline constexpr uint32_t XML_URL = 0x6000;
inline constexpr uint32_t DEVICE_VENDOR_NAME = 0x2000;
inline constexpr uint32_t DEVICE_MODEL_NAME = 0x2020;
inline constexpr uint32_t DEVICE_MANUFACTURER_INFO = 0x2040;
inline constexpr uint32_t DEVICE_VERSION = 0x2070;
inline constexpr uint32_t DEVICE_SERIAL_NUMBER = 0x20B0;
inline constexpr uint32_t DEVICE_USER_ID = 0x20C0;
inline constexpr uint32_t CONNECTION_RESET = 0x4000;
inline constexpr uint32_t DEVICE_CONNECTION_ID = 0x4004;
inline constexpr uint32_t MASTER_HOST_CONNECTION_ID = 0x4008;
inline constexpr uint32_t CONTROL_PACKET_SIZE_MAX = 0x400C;
inline constexpr uint32_t STREAM_PACKET_SIZE_MAX = 0x4010;
inline constexpr uint32_t CONNECTION_CONFIG = 0x4014;
inline constexpr uint32_t CONNECTION_CONFIG_DEFAULT = 0x4018;
inline constexpr uint32_t TEST_MODE = 0x401C;
inline constexpr uint32_t TEST_ERROR_COUNT_SELECTOR = 0x4020;
inline constexpr uint32_t TEST_ERROR_COUNT = 0x4024;
inline constexpr uint32_t TEST_PACKET_COUNT_TX = 0x4028;
inline constexpr uint32_t TEST_PACKET_COUNT_RX = 0x4030;
inline constexpr uint32_t ELECTRICAL_COMPLIANCE_TEST = 0x4038;
inline constexpr uint32_t HS_UPCONNECTION = 0x403C;
inline constexpr uint32_t IMAGE_N_STREAM_ID_ADDRESS = 0x3020;

// ---- Use-case features (§10.3.19-27): bootstrap slot and manufacturer alias ----
inline constexpr uint32_t WIDTH_SLOT = 0x3000;
inline constexpr uint32_t WIDTH_ALIAS = 0x10000;
inline constexpr uint32_t HEIGHT_SLOT = 0x3004;
inline constexpr uint32_t HEIGHT_ALIAS = 0x10004;
inline constexpr uint32_t ACQUISITION_MODE_SLOT = 0x3008;
inline constexpr uint32_t ACQUISITION_MODE_ALIAS = 0x10040;
inline constexpr uint32_t ACQUISITION_START_SLOT = 0x300C;
inline constexpr uint32_t ACQUISITION_START_ALIAS = 0x10010;
inline constexpr uint32_t ACQUISITION_STOP_SLOT = 0x3010;
inline constexpr uint32_t ACQUISITION_STOP_ALIAS = 0x10014;
inline constexpr uint32_t PIXEL_FORMAT_SLOT = 0x3014;
inline constexpr uint32_t PIXEL_FORMAT_ALIAS = 0x10008;
inline constexpr uint32_t TAP_GEOMETRY_SLOT = 0x3018;
inline constexpr uint32_t TAP_GEOMETRY_ALIAS = 0x10028;
inline constexpr uint32_t IMAGE1_STREAM_ID_SLOT = 0x301C;
inline constexpr uint32_t IMAGE1_STREAM_ID_ALIAS = 0x1002C;

// ---- Manufacturer window ----
inline constexpr uint32_t MFR_BASE = 0x10000;
inline constexpr uint32_t MFR_WORDS = 32;
inline constexpr uint32_t MFR_RESERVED1 = 0x1000C;
inline constexpr uint32_t FRAME_COUNT = 0x10018;
inline constexpr uint32_t TEST_PATTERN = 0x1001C;
inline constexpr uint32_t OFFSET_X = 0x10020;
inline constexpr uint32_t OFFSET_Y = 0x10024;
inline constexpr uint32_t SOURCE_TAG = 0x10030;
inline constexpr uint32_t STREAM_FLAGS = 0x10034;
inline constexpr uint32_t TPG_RUN = 0x10038;
inline constexpr uint32_t MFR_RESERVED2 = 0x1003C;

// ---- Power-on values (a ConnectionReset loads *_CONN_RESET) ----
inline constexpr uint32_t XML_MANIFEST_SELECTOR_RESET = 0x0;
inline constexpr uint32_t MASTER_HOST_CONNECTION_ID_RESET = 0x0;
inline constexpr uint32_t STREAM_PACKET_SIZE_MAX_RESET = 0x0;
inline constexpr uint32_t CONNECTION_CONFIG_RESET = 0x10028;
inline constexpr uint32_t TEST_MODE_RESET = 0x0;
inline constexpr uint32_t TEST_ERROR_COUNT_SELECTOR_RESET = 0x0;
inline constexpr uint32_t ELECTRICAL_COMPLIANCE_TEST_RESET = 0x0;
inline constexpr uint32_t WIDTH_RESET = 0x280;
inline constexpr uint32_t HEIGHT_RESET = 0x1E0;
inline constexpr uint32_t ACQUISITION_MODE_RESET = 0x0;
inline constexpr uint32_t ACQUISITION_START_RESET = 0x0;
inline constexpr uint32_t ACQUISITION_STOP_RESET = 0x0;
inline constexpr uint32_t PIXEL_FORMAT_RESET = 0x1080001;
inline constexpr uint32_t TAP_GEOMETRY_RESET = 0x0;
inline constexpr uint32_t IMAGE1_STREAM_ID_RESET = 0x1;
inline constexpr uint32_t MFR_RESERVED1_RESET = 0x0;
inline constexpr uint32_t FRAME_COUNT_RESET = 0x0;
inline constexpr uint32_t TEST_PATTERN_RESET = 0x0;
inline constexpr uint32_t OFFSET_X_RESET = 0x0;
inline constexpr uint32_t OFFSET_Y_RESET = 0x0;
inline constexpr uint32_t SOURCE_TAG_RESET = 0x0;
inline constexpr uint32_t STREAM_FLAGS_RESET = 0x0;
inline constexpr uint32_t TPG_RUN_RESET = 0x1;
inline constexpr uint32_t MFR_RESERVED2_RESET = 0x0;
inline constexpr uint32_t STANDARD_VALUE = 0xC0A79AE5;
inline constexpr uint32_t REVISION_VALUE = 0x10001;
inline constexpr uint32_t XML_MANIFEST_SIZE_VALUE = 0x1;
inline constexpr uint32_t XML_VERSION_VALUE = 0x100;
inline constexpr uint32_t XML_SCHEMA_VERSION_VALUE = 0x10100;
inline constexpr uint32_t XML_URL_ADDRESS_VALUE = 0x6000;
inline constexpr uint32_t IIDC2_ADDRESS_VALUE = 0x0;
inline constexpr uint32_t DEVICE_CONNECTION_ID_VALUE = 0x0;
inline constexpr uint32_t CONTROL_PACKET_SIZE_MAX_VALUE = 0x118;
inline constexpr uint32_t CONNECTION_CONFIG_DEFAULT_VALUE = 0x10028;
inline constexpr uint32_t HS_UPCONNECTION_VALUE = 0x0;

// ---- Strings (NULL-padded to *_LEN bytes on the wire) ----
inline constexpr const char* XML_URL_STR = "Local:cxp_camera.xml;90000000;4357";
inline constexpr uint32_t XML_URL_LEN = 64;
inline constexpr const char* DEVICE_VENDOR_NAME_STR = "AcmeCXP";
inline constexpr uint32_t DEVICE_VENDOR_NAME_LEN = 32;
inline constexpr const char* DEVICE_MODEL_NAME_STR = "CamModel";
inline constexpr uint32_t DEVICE_MODEL_NAME_LEN = 32;
inline constexpr const char* DEVICE_MANUFACTURER_INFO_STR = "AcmeCXP camera";
inline constexpr uint32_t DEVICE_MANUFACTURER_INFO_LEN = 48;
inline constexpr const char* DEVICE_VERSION_STR = "1.1.1";
inline constexpr uint32_t DEVICE_VERSION_LEN = 32;
inline constexpr const char* DEVICE_SERIAL_NUMBER_STR = "SN-0001";
inline constexpr uint32_t DEVICE_SERIAL_NUMBER_LEN = 16;
inline constexpr uint32_t DEVICE_USER_ID_LEN = 16;

// ---- GenICam XML ROM ----
inline constexpr uint32_t XML_BLOB_ADDR = 0x90000000;
inline constexpr uint32_t XML_BLOB_BYTES = 17239;
inline constexpr const char* XML_FILE_NAME = "cxp_camera.xml";

// ---- The map as data (regmodel.py in C++) ----
// A limit that is not there is NONE; `allowed` points at n_allowed values.
inline constexpr int64_t NONE = -1;
enum class Kind : uint8_t { RO, RW, CRST, CNT, STR, NVSTR, ZERO };

struct Row {                       // one Table 45 row
    const char* name;
    uint32_t addr;
    Kind kind;
    uint32_t nbytes;
    uint32_t value;                 // RO constant
    const char* text;               // STR text, else nullptr
    uint32_t reset;                 // RW / CRST power-on value
    int64_t conn_reset;             // value a ConnectionReset loads, or NONE
    int64_t min, max;               // refused below / above (0x41), or NONE
    uint32_t multiple;              // refused unless a multiple of this (0 = any)
    const uint32_t* allowed;        // refused unless one of these (nullptr = any)
    uint32_t n_allowed;
    uint32_t bits;                  // stored bits of an RW row
};

struct Feature {                   // §10.3.19-27 use-case feature
    const char* name;
    uint32_t slot, alias, reset;
    int64_t min, max;
    const uint32_t* allowed;
    uint32_t n_allowed;
    bool write_only;                // a read is refused (0x44)
};

struct Word {                      // manufacturer-window word
    const char* name;
    uint32_t addr, reset;
    int64_t min, max;
    const uint32_t* allowed;
    uint32_t n_allowed;
};

inline constexpr uint32_t CONNECTION_CONFIG_ALLOWED[] = {0x10028};
inline constexpr uint32_t ACQUISITION_MODE_ALLOWED[] = {0x0};
inline constexpr uint32_t PIXEL_FORMAT_ALLOWED[] = {0x1080001, 0x1100003, 0x1100005, 0x1100025, 0x1100007};
inline constexpr uint32_t TAP_GEOMETRY_ALLOWED[] = {0x0};
inline constexpr uint32_t TEST_PATTERN_ALLOWED[] = {0x0, 0x1, 0x2, 0x3};

inline constexpr Row BOOTSTRAP[] = {
    {"Standard", 0x0000, Kind::RO, 4, 0xC0A79AE5, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"Revision", 0x0004, Kind::RO, 4, 0x10001, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"XmlManifestSize", 0x0008, Kind::RO, 4, 0x1, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"XmlManifestSelector", 0x000C, Kind::RW, 4, 0x0, nullptr, 0x0, 0x0, NONE, 0x0, 0, nullptr, 0, 32},
    {"XmlVersion", 0x0010, Kind::RO, 4, 0x100, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"XmlSchemaVersion", 0x0014, Kind::RO, 4, 0x10100, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"XmlUrlAddress", 0x0018, Kind::RO, 4, 0x6000, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"Iidc2Address", 0x001C, Kind::RO, 4, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"XmlUrl", 0x6000, Kind::STR, 64, 0x0, "Local:cxp_camera.xml;90000000;4357", 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"DeviceVendorName", 0x2000, Kind::STR, 32, 0x0, "AcmeCXP", 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"DeviceModelName", 0x2020, Kind::STR, 32, 0x0, "CamModel", 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"DeviceManufacturerInfo", 0x2040, Kind::STR, 48, 0x0, "AcmeCXP camera", 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"DeviceVersion", 0x2070, Kind::STR, 32, 0x0, "1.1.1", 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"DeviceSerialNumber", 0x20B0, Kind::STR, 16, 0x0, "SN-0001", 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"DeviceUserID", 0x20C0, Kind::NVSTR, 16, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"ConnectionReset", 0x4000, Kind::CRST, 4, 0x0, nullptr, 0x0, NONE, NONE, 0x1, 0, nullptr, 0, 32},
    {"DeviceConnectionID", 0x4004, Kind::RO, 4, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"MasterHostConnectionID", 0x4008, Kind::RW, 4, 0x0, nullptr, 0x0, 0x0, NONE, NONE, 0, nullptr, 0, 32},
    {"ControlPacketSizeMax", 0x400C, Kind::RO, 4, 0x118, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"StreamPacketSizeMax", 0x4010, Kind::RW, 4, 0x0, nullptr, 0x0, 0x0, NONE, NONE, 4, nullptr, 0, 32},
    {"ConnectionConfig", 0x4014, Kind::RW, 4, 0x0, nullptr, 0x10028, 0x10028, NONE, NONE, 0, CONNECTION_CONFIG_ALLOWED, 1, 32},
    {"ConnectionConfigDefault", 0x4018, Kind::RO, 4, 0x10028, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"TestMode", 0x401C, Kind::RW, 4, 0x0, nullptr, 0x0, 0x0, NONE, 0x1, 0, nullptr, 0, 1},
    {"TestErrorCountSelector", 0x4020, Kind::RW, 4, 0x0, nullptr, 0x0, 0x0, NONE, 0x0, 0, nullptr, 0, 32},
    {"TestErrorCount", 0x4024, Kind::CNT, 4, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"TestPacketCountTx", 0x4028, Kind::CNT, 8, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"TestPacketCountRx", 0x4030, Kind::CNT, 8, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"ElectricalComplianceTest", 0x4038, Kind::RW, 4, 0x0, nullptr, 0x0, 0x0, NONE, NONE, 0, nullptr, 0, 32},
    {"HsUpconnection", 0x403C, Kind::RO, 4, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
    {"ImageNStreamIdAddress", 0x3020, Kind::ZERO, 4064, 0x0, nullptr, 0x0, NONE, NONE, NONE, 0, nullptr, 0, 32},
};
inline constexpr Feature DEVICE[] = {
    {"Width", 0x3000, 0x10000, 0x280, 0x1, 0x1000, nullptr, 0, false},
    {"Height", 0x3004, 0x10004, 0x1E0, 0x1, 0x1000, nullptr, 0, false},
    {"AcquisitionMode", 0x3008, 0x10040, 0x0, NONE, NONE, ACQUISITION_MODE_ALLOWED, 1, false},
    {"AcquisitionStart", 0x300C, 0x10010, 0x0, NONE, NONE, nullptr, 0, true},
    {"AcquisitionStop", 0x3010, 0x10014, 0x0, NONE, NONE, nullptr, 0, true},
    {"PixelFormat", 0x3014, 0x10008, 0x1080001, NONE, NONE, PIXEL_FORMAT_ALLOWED, 5, false},
    {"TapGeometry", 0x3018, 0x10028, 0x0, NONE, NONE, TAP_GEOMETRY_ALLOWED, 1, false},
    {"Image1StreamID", 0x301C, 0x1002C, 0x1, NONE, 0xFF, nullptr, 0, false},
};
inline constexpr Word MANUFACTURER[] = {
    {"MfrReserved1", 0x1000C, 0x0, NONE, NONE, nullptr, 0},
    {"FrameCount", 0x10018, 0x0, NONE, 0xFFFF, nullptr, 0},
    {"TestPattern", 0x1001C, 0x0, NONE, NONE, TEST_PATTERN_ALLOWED, 4},
    {"OffsetX", 0x10020, 0x0, NONE, 0xFFF, nullptr, 0},
    {"OffsetY", 0x10024, 0x0, NONE, 0xFFF, nullptr, 0},
    {"SourceTag", 0x10030, 0x0, NONE, 0xFFFF, nullptr, 0},
    {"StreamFlags", 0x10034, 0x0, NONE, 0xFF, nullptr, 0},
    {"TpgRun", 0x10038, 0x1, NONE, 0x1, nullptr, 0},
    {"MfrReserved2", 0x1003C, 0x0, NONE, NONE, nullptr, 0},
};

// A value the register does not take (Table 22 code 0x41).
constexpr bool refused(uint32_t v, int64_t min, int64_t max, const uint32_t* allowed,
                       uint32_t n_allowed, uint32_t multiple = 0) {
    if (min != NONE && int64_t(v) < min) return true;
    if (max != NONE && int64_t(v) > max) return true;
    if (multiple && v % multiple) return true;
    if (!allowed) return false;
    for (uint32_t i = 0; i < n_allowed; ++i)
        if (allowed[i] == v) return false;
    return true;
}

}  // namespace cxp::reg
