#!/usr/bin/env python3
"""Generate every view of the register map from src/regmap/cxp_regmap.yaml.

    python3 src/regmap/gen_regmap.py            # write all outputs
    python3 src/regmap/gen_regmap.py --check    # fail if any output is stale

Outputs (paths relative to the repo root) are listed in the YAML header.
The GenICam XML is one of them: it is built in memory first, and the XML
ROM image, its size, the XmlUrl string and XmlVersion / XmlSchemaVersion
all come from those same bytes and the YAML's `genicam:` block.
The register file itself, src/rtl/ctrl/cxp_ctrl_bootstrap_regs.sv, is hand-written
against cxp_regmap_pkg; the YAML's `reg` / `out` / `in` / `nv`
fields name its signals and ports for the Markdown view.
"""

from __future__ import annotations

import argparse
import difflib
import os
import sys
import uuid
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from typing import Dict, List, Optional
from xml.sax.saxutils import escape as xml_escape

import yaml

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "src", "regmap", "cxp_regmap.yaml")

OUT_PKG = "src/rtl/gen/cxp_regmap_pkg.sv"
OUT_PY = "src/model/cxp_protocol/cxp_protocol/regmap.py"
OUT_MODEL = "src/model/cxp_protocol/cxp_protocol/regmodel.py"
OUT_H = "src/regmap/cxp_regmap.h"
OUT_HPP = "src/regmap/cxp_regmap.hpp"
OUT_MD = "docs/design/modules/pkg/cxp_regmap.md"

KINDS = ("RO", "RW", "CRST", "CNT", "STR", "NVSTR", "ZERO")
BANNER = "Generated by src/regmap/gen_regmap.py from src/regmap/cxp_regmap.yaml -- do not edit."


# =============================================================================
# Model
# =============================================================================
@dataclass
class Row:
    name: str
    addr: int
    kind: str
    nbytes: int = 4
    value: object = None
    reg: Optional[str] = None
    reset: int = 0
    conn_reset: Optional[int] = None
    maxv: Optional[int] = None
    max_links: bool = False            # max is p_NUM_LINKS - 1
    wr_pulse: Optional[str] = None
    out: Optional[str] = None
    bits: int = 32
    inp: Optional[str] = None
    nv: Optional[str] = None
    allowed: Optional[List[int]] = None
    minv: Optional[int] = None         # a write below this is refused
    multiple: Optional[int] = None     # a write must be a multiple of this (power of 2)
    entries: Optional[Dict[str, int]] = None  # `allowed` given as name -> value
    gc: Optional[dict] = None          # GenICam feature metadata; None = no feature


@dataclass
class Dev:
    name: str
    slot: int
    alias: int
    reg: str
    reset: int
    out: str
    allowed: Optional[List[int]] = None
    wr_pulse: Optional[str] = None     # output pulsed one cycle after every write
    reset_param: Optional[str] = None  # module parameter holding the power-on value
    minv: Optional[int] = None         # a write below this is refused
    maxv: Optional[int] = None         # a write above this is refused
    wo: bool = False                   # write-only: a read is refused (0x44)
    entries: Optional[Dict[str, int]] = None
    gc: Optional[dict] = None


@dataclass
class Mfr:
    name: str
    off: int
    reg: str
    out: Optional[str] = None
    reset: int = 0                     # power-on value
    minv: Optional[int] = None         # a write below this is refused
    maxv: Optional[int] = None         # a write above this is refused
    allowed: Optional[List[int]] = None
    entries: Optional[Dict[str, int]] = None
    gc: Optional[dict] = None


@dataclass
class Feat:
    """One GenICam feature and the register node behind it."""
    name: str
    type: str                          # Integer / Enumeration / Command / String / Boolean
    ns: str                            # NameSpace: Standard / Custom
    gc: dict
    addr: int
    length: int
    access: str                        # RO / RW / WO
    minv: Optional[int] = None
    maxv: Optional[int] = None
    inc: Optional[int] = None
    entries: Optional[Dict[str, int]] = None

    @property
    def reg(self) -> str:
        return f"{self.name}Reg"


@dataclass
class Map:
    module: str
    xml: dict
    mfr_base: int
    mfr_words: int
    rows: List[Row]
    dev: List[Dev]
    mfr: List[Mfr]
    gc: dict = None                    # the `genicam:` block
    xml_bytes: bytes = b""

    @property
    def blob_bytes(self) -> int:
        return len(self.xml_bytes)

    @property
    def blob_words(self) -> int:
        return (len(self.xml_bytes) + 3) // 4

    @property
    def xml_url(self) -> str:
        return f"Local:{self.xml['name']};{self.xml['blob_addr']:08X};{self.blob_bytes:X}"

    def kind(self, k: str) -> List[Row]:
        return [r for r in self.rows if r.kind == k]

    def one(self, k: str) -> Row:
        rows = self.kind(k)
        if len(rows) != 1:
            raise SystemExit(f"regmap: expected exactly one {k} row, found {len(rows)}")
        return rows[0]


def _version_word(v: dict) -> int:
    """§10.3.9-10: major << 16 | minor << 8 | sub-minor."""
    return (v["major"] << 16) | (v["minor"] << 8) | v.get("subminor", 0)


def _resolve(ns: dict, v):
    """`xml.<key>` / `genicam.<key>` in a row value names a computed value."""
    if isinstance(v, str) and "." in v and v.split(".", 1)[0] in ns:
        top, key = v.split(".", 1)
        return ns[top][key]
    return v


def _allowed(v):
    """`allowed` as (list of values, entry mapping or None)."""
    if isinstance(v, dict):
        return list(v.values()), dict(v)
    return v, None


def load() -> Map:
    with open(SRC) as f:
        y = yaml.safe_load(f)
    xml = dict(y["xml"])
    m = Map(module=y["module"], xml=xml, mfr_base=y["mfr"]["base"],
            mfr_words=y["mfr"]["words"], rows=[], dev=[], mfr=[], gc=dict(y["genicam"]))
    ns = {"xml": xml, "genicam": m.gc}
    for r in y["registers"]:
        if r["kind"] not in KINDS:
            raise SystemExit(f"{r['name']}: unknown kind {r['kind']}")
        allowed, entries = _allowed(r.get("allowed"))
        m.rows.append(Row(
            name=r["name"], addr=int(_resolve(ns, r["addr"])), kind=r["kind"],
            nbytes=r.get("len", 4), value=r.get("value"),
            reg=r.get("reg"), reset=r.get("reset", 0), conn_reset=r.get("conn_reset"),
            maxv=0 if r.get("max") == "links" else r.get("max"),
            max_links=r.get("max") == "links", wr_pulse=r.get("wr_pulse"),
            out=r.get("out"), bits=r.get("bits", 32), inp=r.get("in"), nv=r.get("nv"),
            allowed=allowed, minv=r.get("min"), multiple=r.get("multiple"),
            entries=entries, gc=r.get("gc")))
    for d in y["device"]:
        allowed, entries = _allowed(d.get("allowed"))
        m.dev.append(Dev(name=d["name"], slot=d["slot"], alias=d.get("alias", 0),
                         reg=d["reg"], reset=d["reset"], out=d["out"],
                         allowed=allowed, entries=entries, gc=d.get("gc"),
                         wr_pulse=d.get("wr_pulse"), reset_param=d.get("reset_param"),
                         minv=d.get("min"), maxv=d.get("max"), wo=d.get("access") == "WO"))
    for w in y["manufacturer"]:
        allowed, entries = _allowed(w.get("allowed"))
        m.mfr.append(Mfr(name=w["name"], off=w["offset"], reg=w["reg"], out=w.get("out"),
                         reset=w.get("reset", 0), minv=w.get("min"), maxv=w.get("max"),
                         allowed=allowed, entries=entries, gc=w.get("gc")))
    # The XML first; every value that depends on it comes from its bytes.
    text = gen_xml(m)
    m.xml_bytes = text.encode("utf-8")
    xml["version"] = _version_word(m.gc["version"])
    xml["schema_version"] = _version_word(m.gc["schema"])
    xml["url"] = m.xml_url
    for r in m.rows:
        r.value = _resolve(ns, r.value)
    _validate(m)
    _xml_selfcheck(m, text)
    return m


def _validate(m: Map) -> None:
    seen: Dict[int, str] = {}
    for r in m.rows:
        if r.addr & 3:
            raise SystemExit(f"{r.name}: address 0x{r.addr:X} not word-aligned")
        if r.addr > 0xFFFF:
            raise SystemExit(f"{r.name}: bootstrap rows decode 16 address bits")
        for w in range((r.nbytes + 3) // 4):
            a = r.addr + 4 * w
            if a in seen:
                raise SystemExit(f"{r.name}: 0x{a:04X} overlaps {seen[a]}")
            seen[a] = r.name
        # §10.3.28: the device executes a connection reset at power-up, so a
        # register with a ConnectionReset value powers up at that value.
        if r.conn_reset is not None and r.conn_reset != r.reset:
            raise SystemExit(f"{r.name}: reset 0x{r.reset:X} != conn_reset 0x{r.conn_reset:X} "
                             "(power-up executes a connection reset, §10.3.28)")
        if r.kind == "NVSTR" and (r.nbytes != 16 or r.addr & 0xF):
            raise SystemExit(f"{r.name}: NVSTR must be 16 bytes on a 16-byte boundary")
        if r.kind == "CNT" and not r.out:
            raise SystemExit(f"{r.name}: CNT needs `out`, its clear pulse")
        if r.kind == "STR" and len(str(r.value)) > r.nbytes:
            raise SystemExit(f"{r.name}: '{r.value}' longer than {r.nbytes} bytes")
        if r.allowed is not None and r.kind != "RW":
            raise SystemExit(f"{r.name}: `allowed` needs an RW row")
        if (r.maxv is not None or r.minv is not None or r.multiple) and r.kind not in ("RW", "CRST"):
            raise SystemExit(f"{r.name}: `min` / `max` / `multiple` need an RW or CRST row")
        if r.multiple and r.multiple & (r.multiple - 1):
            raise SystemExit(f"{r.name}: `multiple` must be a power of 2")
        if r.allowed is not None and r.reset not in r.allowed:
            raise SystemExit(f"{r.name}: power-on value not in `allowed`")
    for d in m.dev:
        if d.slot in seen:
            raise SystemExit(f"{d.name}: slot 0x{d.slot:04X} overlaps {seen[d.slot]}")
        if not (m.mfr_base <= d.alias < m.mfr_base + 4 * m.mfr_words):
            raise SystemExit(f"{d.name}: feature address 0x{d.alias:X} outside the manufacturer window")
    if m.mfr_words & (m.mfr_words - 1):
        raise SystemExit("mfr.words must be a power of two")
    offs = {w.off for w in m.mfr}
    for d in m.dev:
        if d.alias and d.alias - m.mfr_base in offs:
            raise SystemExit(f"{d.name}: alias overlaps a manufacturer word")
    if m.xml_url and len(m.xml_url) > 64:
        raise SystemExit("XmlUrl longer than its 64-byte field")


# =============================================================================
# Helpers
# =============================================================================
def const(name: str) -> str:
    """CamelCase register name -> UPPER_SNAKE constant stem."""
    out = []
    for i, c in enumerate(name):
        if c.isupper() and i and (not name[i - 1].isupper()
                                  or (i + 1 < len(name) and name[i + 1].islower())):
            out.append("_")
        out.append(c.upper())
    return "".join(out).replace("__", "_")


def h32(v: int) -> str:
    return f"32'h{v >> 16:04X}_{v & 0xFFFF:04X}"


def h16(v: int) -> str:
    return f"16'h{v:04X}"


def sv_str(s: str, nbytes: int) -> str:
    """Big-endian, NULL-padded string literal of exactly nbytes bytes."""
    pad = nbytes - len(s)
    body = f'"{s}"' if s else ""
    if pad and body:
        return "{" + body + f", {{{pad}{{8'h00}}}}" + "}"
    if pad:
        return f"{{{pad}{{8'h00}}}}"
    return body


def pad(s: str, n: int) -> str:
    return s + " " * max(1, n - len(s))


# =============================================================================
# cxp_regmap_pkg.sv
# =============================================================================
def gen_pkg(m: Map) -> str:
    L: List[str] = []
    a = L.append
    a("/*")
    a("=" * 80)
    a("  cxp_regmap_pkg")
    a("  CoaXPress 1.1.1 — register map constants (Table 45 + manufacturer space).")
    a("=" * 80)
    a("")
    a(f"    {BANNER}")
    a("")
    a("    Description:")
    a("      Addresses, power-on values and the GenICam XML ROM geometry used by")
    a("      cxp_ctrl_bootstrap_regs, the register router and the benches.  Change")
    a("      src/regmap/cxp_regmap.yaml and run `make regmap` instead of editing.")
    a("")
    a("================================================================*/")
    a("")
    a("`timescale 1ns / 1ns")
    a("")
    a("package cxp_regmap_pkg;")
    a("")
    a("    //=======================================================================")
    a("    // Bootstrap registers (low 16 address bits)")
    a("    //=======================================================================")
    a("")
    for r in m.rows:
        a(f"    localparam logic [15:0] {pad(const(r.name) + '_ADDR', 34)}= {h16(r.addr)};")
    a("")
    a("    //=======================================================================")
    a("    // Use-case feature registers: 0x3000 slot and manufacturer alias")
    a("    //=======================================================================")
    a("")
    for d in m.dev:
        a(f"    localparam logic [15:0] {pad(const(d.name) + '_SLOT', 34)}= {h16(d.slot)};")
        a(f"    localparam logic [31:0] {pad(const(d.name) + '_ALIAS', 34)}= {h32(d.alias)};")
    a("")
    a("    //=======================================================================")
    a("    // Manufacturer window")
    a("    //=======================================================================")
    a("")
    a(f"    localparam logic [31:0] {pad('MFR_BASE', 34)}= {h32(m.mfr_base)};")
    a(f"    localparam int          {pad('MFR_WORDS', 34)}= {m.mfr_words};")
    for w in m.mfr:
        a(f"    localparam logic [31:0] {pad(const(w.name) + '_ADDR', 34)}= {h32(m.mfr_base + w.off)};")
    a("")
    a("    //=======================================================================")
    a("    // Power-on values")
    a("    //=======================================================================")
    a("")
    for r in m.kind("RW"):
        a(f"    localparam logic [31:0] {pad(const(r.name) + '_RESET', 34)}= {h32(r.reset)};")
        if r.conn_reset is not None and r.conn_reset != 0:
            a(f"    localparam logic [31:0] {pad(const(r.name) + '_CONN_RESET', 34)}= {h32(r.conn_reset)};")
    for d in m.dev:
        a(f"    localparam logic [31:0] {pad(const(d.name) + '_RESET', 34)}= {h32(d.reset)};")
    for r in m.kind("RO"):
        a(f"    localparam logic [31:0] {pad(const(r.name) + '_VALUE', 34)}= {h32(int(r.value))};")
    a("")
    a("    //=======================================================================")
    a("    // Read-only strings (NULL-padded to the row length on the wire)")
    a("    //=======================================================================")
    a("")
    for r in m.kind("STR"):
        a(f"    localparam string       {pad(const(r.name) + '_STR', 34)}= \"{r.value}\";")
    a("")
    a("    //=======================================================================")
    a("    // Address windows seen by the register router")
    a("    //=======================================================================")
    a("")
    boot_end = max(r.addr + ((r.nbytes + 3) // 4) * 4 for r in m.rows if r.addr < m.xml["url_addr"])
    a("    // Last byte of the bootstrap block the router forwards (0x40FF: the")
    a("    // Table 45 CXP group rounded up to its 256-byte page).")
    a(f"    localparam logic [31:0] {pad('BOOTSTRAP_END', 34)}= {h32((boot_end | 0xFF))};")
    a("")
    a("    //=======================================================================")
    a("    // GenICam XML ROM")
    a("    //=======================================================================")
    a("")
    a(f"    localparam logic [31:0] {pad('XML_BLOB_ADDR', 34)}= {h32(m.xml['blob_addr'])};")
    a(f"    localparam logic [31:0] {pad('XML_BLOB_BYTES', 34)}= {h32(m.blob_bytes)};   // {m.blob_bytes}")
    a(f"    localparam int          {pad('XML_BLOB_WORDS', 34)}= {m.blob_words};")
    a(f"    localparam string       {pad('XML_BLOB_MEM', 34)}= \"{os.path.basename(m.xml['mem'])}\";")
    a("")
    a("endpackage")
    a("")
    return "\n".join(L)


# =============================================================================
# GenICam XML (GenApi schema 1.1)
# =============================================================================
GENAPI_NS = "http://www.genicam.org/GenApi/Version_1_1"
GENAPI_XSD = "http://www.genicam.org/GenApi/GenApiSchema_Version_1_1.xsd"
GC_KEYS = {"feature", "type", "category", "description", "tooltip", "display", "visibility",
           "representation", "unit", "streamable", "namespace", "selects", "nocache"}
GC_TYPES = ("Integer", "Enumeration", "Command", "String", "Boolean")


def _int_limits(name: str, minv, maxv, allowed, multiple, nbytes: int):
    """(Min, Max, Inc) of an Integer feature: what the register takes."""
    if allowed is not None:
        vs = sorted(allowed)
        if vs != list(range(vs[0], vs[-1] + 1)):
            raise SystemExit(f"{name}: an Integer's `allowed` must be a range; "
                             "name the values (a mapping) to make it an Enumeration")
        return vs[0], vs[-1], None
    if minv is None and maxv is None and not multiple:
        return None, None, None
    top = (1 << (8 * nbytes)) - 1
    if maxv is None and multiple:
        maxv = top // multiple * multiple
    return (minv or 0), maxv, multiple


def features(m: Map) -> List[Feat]:
    """Every row with `gc:` as a feature, in map order."""
    out: List[Feat] = []

    def add(x, addr: int, nbytes: int, access: str, kind: str, ns: str, multiple=None) -> None:
        gc = dict(x.gc)
        bad = set(gc) - GC_KEYS
        if bad:
            raise SystemExit(f"{x.name}: unknown gc key(s) {sorted(bad)}")
        if kind in ("STR", "NVSTR"):
            typ = "String"
        elif access == "WO":
            typ = "Command"
        elif x.entries:
            typ = "Enumeration"
        else:
            typ = "Integer"
        typ = gc.get("type", typ)
        if typ not in GC_TYPES:
            raise SystemExit(f"{x.name}: gc.type {typ} is not one of {GC_TYPES}")
        if typ == "Enumeration" and not x.entries:
            raise SystemExit(f"{x.name}: an Enumeration needs `allowed` as a name -> value mapping")
        f = Feat(name=gc.get("feature", x.name), type=typ, ns=gc.get("namespace", ns), gc=gc,
                 addr=addr, length=nbytes, access=access, entries=x.entries)
        if typ in ("Integer", "Boolean"):
            f.minv, f.maxv, f.inc = _int_limits(x.name, x.minv, x.maxv, x.allowed, multiple, nbytes)
        out.append(f)

    for r in m.rows:
        if r.gc is None:
            continue
        if r.kind not in ("RO", "RW", "CNT", "STR", "NVSTR"):
            raise SystemExit(f"{r.name}: a {r.kind} row cannot be a GenICam feature")
        acc = "RO" if r.kind in ("RO", "STR") else "RW"
        add(r, r.addr, r.nbytes, acc, r.kind, "Standard", r.multiple)
    for d in m.dev:
        if d.gc is not None:
            add(d, d.alias, 4, "WO" if d.wo else "RW", "RW", "Standard")
    for w in m.mfr:
        if w.gc is not None:
            add(w, m.mfr_base + w.off, 4, "RW", "RW", "Custom")
    names = [f.name for f in out]
    dup = {n for n in names if names.count(n) > 1}
    if dup:
        raise SystemExit(f"GenICam feature name(s) used twice: {sorted(dup)}")
    return out


def _x(s) -> str:
    return xml_escape(" ".join(str(s).split()))


def _num(v: int) -> str:
    return str(v) if v < 0x100 else f"0x{v:04X}"


def _addr(v: int) -> str:
    return f"0x{v:04X}"


def gen_xml(m: Map) -> str:
    """The GenICam description of the device, GenApi schema 1.1."""
    g = m.gc
    feats = features(m)
    cats = g["categories"]
    cat_names = [c["name"] for c in cats]
    for f in feats:
        if f.gc.get("category") not in cat_names:
            raise SystemExit(f"{f.name}: gc.category {f.gc.get('category')!r} is not in genicam.categories")
    port = g["port"]
    L: List[str] = []
    a = L.append
    ver, sch = g["version"], g["schema"]
    a('<?xml version="1.0" encoding="UTF-8"?>')
    a("<!--")
    a(f"  {BANNER.replace(' -- ', '; ')}")              # no "--" in an XML comment
    a("  GenICam description of the CoaXPress 1.1.1 device IP (GenApi schema")
    a(f"  {sch['major']}.{sch['minor']}.{sch.get('subminor', 0)}), served from the XML ROM at "
      f"0x{m.xml['blob_addr']:08X}; XmlUrl at 0x{m.xml['url_addr']:04X}.")
    a("-->")
    a("<RegisterDescription")
    a(f'    ModelName="{_x(g["model"])}"')
    a(f'    VendorName="{_x(g["vendor"])}"')
    a(f'    ToolTip="{_x(g["tooltip"])}"')
    a(f'    StandardNameSpace="{g["standard_namespace"]}"')
    a(f'    SchemaMajorVersion="{sch["major"]}" SchemaMinorVersion="{sch["minor"]}" '
      f'SchemaSubMinorVersion="{sch.get("subminor", 0)}"')
    a(f'    MajorVersion="{ver["major"]}" MinorVersion="{ver["minor"]}" '
      f'SubMinorVersion="{ver.get("subminor", 0)}"')
    a(f'    ProductGuid="{g["product_guid"]}"')
    a('    VersionGuid="@VERSION_GUID@"')
    a(f'    xmlns="{GENAPI_NS}"')
    a('    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"')
    a(f'    xsi:schemaLocation="{GENAPI_NS} {GENAPI_XSD}">')

    def common(gc: dict) -> None:
        # ToolTip, Description, DisplayName, Visibility: the schema's order.
        for key, tag in (("tooltip", "ToolTip"), ("description", "Description"),
                         ("display", "DisplayName"), ("visibility", "Visibility")):
            if gc.get(key):
                a(f"    <{tag}>{_x(gc[key])}</{tag}>")

    for c in cats:
        bad = set(c) - {"name", "description", "tooltip", "display", "visibility",
                        "namespace", "children"}
        if bad:
            raise SystemExit(f"category {c['name']}: unknown key(s) {sorted(bad)}")
        a("")
        a(f'  <Category Name="{c["name"]}" NameSpace="{c.get("namespace", "Standard")}">')
        common(c)
        for f in feats:
            if f.gc["category"] == c["name"]:
                a(f"    <pFeature>{f.name}</pFeature>")
        for k in c.get("children", []):
            if k not in cat_names:
                raise SystemExit(f"category {c['name']}: child {k} is not a category")
            a(f"    <pFeature>{k}</pFeature>")
        a("  </Category>")

    for c in cats:
        for f in feats:
            if f.gc["category"] != c["name"]:
                continue
            gc = f.gc
            a("")
            a(f'  <{f.type} Name="{f.name}" NameSpace="{f.ns}">')
            common(gc)
            if "streamable" in gc:
                a(f"    <Streamable>{'Yes' if gc['streamable'] else 'No'}</Streamable>")
            if f.type == "Enumeration":
                for en, ev in f.entries.items():
                    a(f'    <EnumEntry Name="{en}"><Value>{_num(ev)}</Value></EnumEntry>')
            a(f"    <pValue>{f.reg}</pValue>")
            if f.type == "Command":
                a("    <CommandValue>1</CommandValue>")       # §11.2.1.4-5: single-shot 1
            if f.type == "Integer":
                lim = _num if gc.get("representation") == "HexNumber" else str
                if f.minv is not None:
                    a(f"    <Min>{lim(f.minv)}</Min>")
                if f.maxv is not None:
                    a(f"    <Max>{lim(f.maxv)}</Max>")
                if f.inc:
                    a(f"    <Inc>{f.inc}</Inc>")
                if gc.get("representation"):
                    a(f"    <Representation>{gc['representation']}</Representation>")
                if gc.get("unit"):
                    a(f"    <Unit>{_x(gc['unit'])}</Unit>")
                for s in gc.get("selects", []):
                    a(f"    <pSelected>{s}</pSelected>")
            elif f.type == "Boolean":
                a("    <OnValue>1</OnValue>")
                a("    <OffValue>0</OffValue>")
            a(f"  </{f.type}>")
            tag = "StringReg" if f.type == "String" else "IntReg"
            a(f'  <{tag} Name="{f.reg}">')
            a(f"    <Address>{_addr(f.addr)}</Address><Length>{f.length}</Length>"
              f"<AccessMode>{f.access}</AccessMode>")
            tail = f"<pPort>{port}</pPort>"
            if gc.get("nocache"):
                tail += "<Cachable>NoCache</Cachable>"
            if tag == "IntReg":                               # §10.3.3: big-endian
                tail += "<Sign>Unsigned</Sign><Endianess>BigEndian</Endianess>"
            a(f"    {tail}")
            a(f"  </{tag}>")

    a("")
    a(f'  <Port Name="{port}" NameSpace="Standard"/>')
    a("")
    a("</RegisterDescription>")
    a("")
    text = "\n".join(L)
    # The VersionGuid names this exact file: a UUIDv5 of its content.
    vg = uuid.uuid5(uuid.UUID(g["product_guid"]), text)
    return text.replace("@VERSION_GUID@", str(vg))


def _xml_selfcheck(m: Map, text: str) -> None:
    """Structural check of the generated tree: every node reference
    resolves, every feature hangs under Root, every register node is a
    register of the map with the map's access mode."""
    root = ET.fromstring(text)
    nodes = {}
    for el in root:
        tag = el.tag.split("}", 1)[-1]
        nodes[el.get("Name")] = (tag, el)
    q = lambda el, t: el.findall(f"{{{GENAPI_NS}}}{t}")
    for name, (tag, el) in nodes.items():
        for t in ("pFeature", "pValue", "pPort", "pSelected"):
            for ref in q(el, t):
                if ref.text not in nodes:
                    raise SystemExit(f"XML {name}: <{t}>{ref.text}</{t}> names no node")
    reached, todo = set(), ["Root"]
    while todo:
        n = todo.pop()
        reached.add(n)
        todo += [p.text for p in q(nodes[n][1], "pFeature") if p.text not in reached]
    decoded = set()
    for r in m.rows:
        decoded.update(range(r.addr, r.addr + r.nbytes, 4))
    decoded.update(d.alias for d in m.dev)
    decoded.update(m.mfr_base + w.off for w in m.mfr)
    for name, (tag, el) in nodes.items():
        if tag in ("IntReg", "StringReg"):
            a = int(q(el, "Address")[0].text, 0)
            if a not in decoded:
                raise SystemExit(f"XML {name}: address 0x{a:X} is not a register of the map")
        elif tag not in ("Category", "Port") and name not in reached:
            raise SystemExit(f"XML {name}: not under Root")


# =============================================================================
# XML ROM image
# =============================================================================
def gen_mem(m: Map) -> str:
    data = m.xml_bytes + b"\x00" * ((-len(m.xml_bytes)) % 4)
    return "".join(f"{int.from_bytes(data[i:i + 4], 'big'):08X}\n" for i in range(0, len(data), 4))


# =============================================================================
# Python / C / Markdown views
# =============================================================================
def gen_py(m: Map) -> str:
    L = [f'"""CoaXPress register map.  {BANNER}"""', "", "import os as _os", "", ""]
    a = L.append
    a("# Bootstrap registers (§10.3, Table 45)")
    for r in m.rows:
        a(f"{const(r.name)} = 0x{r.addr:04X}")
    a("")
    a("# Use-case features: bootstrap slot and manufacturer alias")
    for d in m.dev:
        a(f"{const(d.name)}_SLOT = 0x{d.slot:04X}")
        if d.alias:
            a(f"{const(d.name)}_ALIAS = 0x{d.alias:X}")
    a("")
    a("# Manufacturer window")
    a(f"MFR_BASE = 0x{m.mfr_base:X}")
    for w in m.mfr:
        a(f"{const(w.name)} = 0x{m.mfr_base + w.off:X}")
    a("")
    a("# Power-on values")
    for r in m.kind("RW"):
        a(f"{const(r.name)}_RESET = 0x{r.reset:X}")
    for d in m.dev:
        a(f"{const(d.name)}_RESET = {d.reset}")
    for r in m.kind("RO"):
        a(f"{const(r.name)}_VALUE = 0x{int(r.value):X}")
    a("")
    a("# Strings")
    for r in m.kind("STR"):
        a(f"{const(r.name)}_STR = {str(r.value)!r}")
        a(f"{const(r.name)}_LEN = {r.nbytes}")
    a("")
    a("# GenICam XML ROM")
    a(f"XML_BLOB_ADDR = 0x{m.xml['blob_addr']:08X}")
    a(f"XML_BLOB_BYTES = {m.blob_bytes}")
    up = ", ".join(['".."'] * (OUT_PY.count("/")))
    a("")
    a("# The generated files, by absolute path: the XML and its ROM image")
    a(f"_ROOT = _os.path.abspath(_os.path.join(_os.path.dirname(__file__), {up}))")
    a(f"XML_FILE = _os.path.join(_ROOT, {m.xml['file']!r})")
    a(f"XML_MEM = _os.path.join(_ROOT, {m.xml['mem']!r})")
    a("")
    a("")
    a("def xml_blob() -> bytes:")
    a('    """The bytes the XML ROM serves (the generated XML file)."""')
    a("    with open(XML_FILE, \"rb\") as f:")
    a("        return f.read()")
    a("")
    return "\n".join(L)


def gen_h(m: Map) -> str:
    L = [f"/* CoaXPress register map.  {BANNER} */", "#ifndef CXP_REGMAP_H",
         "#define CXP_REGMAP_H", ""]
    a = L.append
    for r in m.rows:
        a(f"#define CXP_REG_{const(r.name)} 0x{r.addr:04X}u")
    for d in m.dev:
        a(f"#define CXP_REG_{const(d.name)}_SLOT 0x{d.slot:04X}u")
        if d.alias:
            a(f"#define CXP_REG_{const(d.name)}_ALIAS 0x{d.alias:X}u")
    a(f"#define CXP_REG_MFR_BASE 0x{m.mfr_base:X}u")
    for w in m.mfr:
        a(f"#define CXP_REG_{const(w.name)} 0x{m.mfr_base + w.off:X}u")
    a(f"#define CXP_XML_BLOB_ADDR 0x{m.xml['blob_addr']:08X}u")
    a(f"#define CXP_XML_BLOB_BYTES {m.blob_bytes}u")
    a(f'#define CXP_XML_URL "{m.xml_url}"')
    a("")
    a("#endif /* CXP_REGMAP_H */")
    a("")
    return "\n".join(L)


def _cpp_opt(v: Optional[int]) -> str:
    return "NONE" if v is None else f"0x{v:X}"


def gen_hpp(m: Map) -> str:
    """The map for C++ (src/emu/host): constants and the row tables a
    reference device decodes with (the same data as regmodel.py)."""
    L = [f"// CoaXPress register map.  {BANNER}", "#pragma once", "",
         "#include <cstdint>", "", "namespace cxp::reg {", ""]
    a = L.append

    def c(name: str, v, typ: str = "uint32_t") -> None:
        a(f"inline constexpr {typ} {name} = {v};")

    a("// ---- Bootstrap registers (§10.3, Table 45) ----")
    for r in m.rows:
        c(const(r.name), f"0x{r.addr:04X}")
    a("")
    a("// ---- Use-case features (§10.3.19-27): bootstrap slot and manufacturer alias ----")
    for d in m.dev:
        c(f"{const(d.name)}_SLOT", f"0x{d.slot:04X}")
        c(f"{const(d.name)}_ALIAS", f"0x{d.alias:X}")
    a("")
    a("// ---- Manufacturer window ----")
    c("MFR_BASE", f"0x{m.mfr_base:X}")
    c("MFR_WORDS", m.mfr_words)
    for w in m.mfr:
        c(const(w.name), f"0x{m.mfr_base + w.off:X}")
    a("")
    a("// ---- Power-on values (a ConnectionReset loads *_CONN_RESET) ----")
    for r in m.kind("RW"):
        c(f"{const(r.name)}_RESET", f"0x{r.reset:X}")
    for d in m.dev:
        c(f"{const(d.name)}_RESET", f"0x{d.reset:X}")
    for w in m.mfr:
        c(f"{const(w.name)}_RESET", f"0x{w.reset:X}")
    for r in m.kind("RO"):
        c(f"{const(r.name)}_VALUE", f"0x{int(r.value):X}")
    a("")
    a("// ---- Strings (NULL-padded to *_LEN bytes on the wire) ----")
    for r in m.kind("STR"):
        c(f"{const(r.name)}_STR", f'"{r.value}"', "const char*")
        c(f"{const(r.name)}_LEN", r.nbytes)
    for r in m.kind("NVSTR"):
        c(f"{const(r.name)}_LEN", r.nbytes)
    a("")
    a("// ---- GenICam XML ROM ----")
    c("XML_BLOB_ADDR", f"0x{m.xml['blob_addr']:08X}")
    c("XML_BLOB_BYTES", m.blob_bytes)
    # The XmlUrl text is XML_URL_STR above; XML_URL is its address.
    c("XML_FILE_NAME", f'"{m.xml["name"]}"', "const char*")
    a("")
    a("// ---- The map as data (regmodel.py in C++) ----")
    a("// A limit that is not there is NONE; `allowed` points at n_allowed values.")
    a("inline constexpr int64_t NONE = -1;")
    a("enum class Kind : uint8_t { RO, RW, CRST, CNT, STR, NVSTR, ZERO };")
    a("")
    a("struct Row {                       // one Table 45 row")
    a("    const char* name;")
    a("    uint32_t addr;")
    a("    Kind kind;")
    a("    uint32_t nbytes;")
    a("    uint32_t value;                 // RO constant")
    a("    const char* text;               // STR text, else nullptr")
    a("    uint32_t reset;                 // RW / CRST power-on value")
    a("    int64_t conn_reset;             // value a ConnectionReset loads, or NONE")
    a("    int64_t min, max;               // refused below / above (0x41), or NONE")
    a("    uint32_t multiple;              // refused unless a multiple of this (0 = any)")
    a("    const uint32_t* allowed;        // refused unless one of these (nullptr = any)")
    a("    uint32_t n_allowed;")
    a("    uint32_t bits;                  // stored bits of an RW row")
    a("};")
    a("")
    a("struct Feature {                   // §10.3.19-27 use-case feature")
    a("    const char* name;")
    a("    uint32_t slot, alias, reset;")
    a("    int64_t min, max;")
    a("    const uint32_t* allowed;")
    a("    uint32_t n_allowed;")
    a("    bool write_only;                // a read is refused (0x44)")
    a("};")
    a("")
    a("struct Word {                      // manufacturer-window word")
    a("    const char* name;")
    a("    uint32_t addr, reset;")
    a("    int64_t min, max;")
    a("    const uint32_t* allowed;")
    a("    uint32_t n_allowed;")
    a("};")
    a("")

    def allowed(name: str, vs) -> str:
        if vs is None:
            return "nullptr, 0"
        a(f"inline constexpr uint32_t {const(name)}_ALLOWED[] = {{"
          + ", ".join(f"0x{v:X}" for v in vs) + "};")
        return f"{const(name)}_ALLOWED, {len(vs)}"

    rows = []
    for r in m.rows:
        al = allowed(r.name, r.allowed)
        val = 0 if r.kind != "RO" else int(r.value)
        txt = f'"{r.value}"' if r.kind == "STR" else "nullptr"
        crs = "NONE" if r.conn_reset is None else f"0x{r.conn_reset:X}"
        rows.append(f'    {{"{r.name}", 0x{r.addr:04X}, Kind::{r.kind}, {r.nbytes}, 0x{val:X}, {txt}, '
                    f"0x{r.reset:X}, {crs}, {_cpp_opt(r.minv)}, {_cpp_opt(r.maxv)}, "
                    f"{r.multiple or 0}, {al}, {r.bits}}},")
    devs = []
    for d in m.dev:
        al = allowed(d.name, d.allowed)
        devs.append(f'    {{"{d.name}", 0x{d.slot:04X}, 0x{d.alias:X}, 0x{d.reset:X}, '
                    f"{_cpp_opt(d.minv)}, {_cpp_opt(d.maxv)}, {al}, {'true' if d.wo else 'false'}}},")
    words = []
    for w in m.mfr:
        al = allowed(w.name, w.allowed)
        words.append(f'    {{"{w.name}", 0x{m.mfr_base + w.off:X}, 0x{w.reset:X}, '
                     f"{_cpp_opt(w.minv)}, {_cpp_opt(w.maxv)}, {al}}},")
    a("")
    a("inline constexpr Row BOOTSTRAP[] = {")
    L.extend(rows)
    a("};")
    a("inline constexpr Feature DEVICE[] = {")
    L.extend(devs)
    a("};")
    a("inline constexpr Word MANUFACTURER[] = {")
    L.extend(words)
    a("};")
    a("")
    a("// A value the register does not take (Table 22 code 0x41).")
    a("constexpr bool refused(uint32_t v, int64_t min, int64_t max, const uint32_t* allowed,")
    a("                       uint32_t n_allowed, uint32_t multiple = 0) {")
    a("    if (min != NONE && int64_t(v) < min) return true;")
    a("    if (max != NONE && int64_t(v) > max) return true;")
    a("    if (multiple && v % multiple) return true;")
    a("    if (!allowed) return false;")
    a("    for (uint32_t i = 0; i < n_allowed; ++i)")
    a("        if (allowed[i] == v) return false;")
    a("    return true;")
    a("}")
    a("")
    a("}  // namespace cxp::reg")
    a("")
    return "\n".join(L)


def _opt(v: Optional[int]) -> str:
    return "None" if v is None else f"0x{v:X}"


def _tup(vs: Optional[List[int]]) -> str:
    return "None" if vs is None else "(" + ", ".join(f"0x{v:X}" for v in vs) + ",)"


def gen_regmodel(m: Map) -> str:
    """The register map as data a reference model can execute.

    `cxp_protocol.regref` turns this into the answer a host should get
    for any read or write — value and Table 22 code — so a testbench can
    check a device's control channel against the map rather than against
    a second hand-written list of addresses.
    """
    L = [f'"""Register map as data for the reference model.  {BANNER}"""',
         "", "from __future__ import annotations", "",
         "# One entry per bootstrap row (Table 45), in address order:",
         "#   name, addr, kind, nbytes, value, reset, conn_reset, max,",
         "#   allowed, bits, min, multiple",
         "# `value` is the constant of an RO row or the text of a STR row;",
         "# `conn_reset` is the value §10.3.28 loads, or None to leave it.",
         "BOOTSTRAP = ("]
    a = L.append
    for r in m.rows:
        val = repr(r.value) if isinstance(r.value, str) else (
            "None" if r.value is None else f"0x{int(r.value):X}")
        crs = "None" if r.conn_reset is None else f"0x{r.conn_reset:X}"
        mx = "None" if r.maxv is None else f"0x{r.maxv:X}"
        al = ("None" if r.allowed is None
              else "(" + ", ".join(f"0x{v:X}" for v in r.allowed) + ",)")
        a(f'    ("{r.name}", 0x{r.addr:04X}, "{r.kind}", {r.nbytes}, {val}, '
          f"0x{r.reset:X}, {crs}, {mx}, {al}, {r.bits}, {_opt(r.minv)}, {_opt(r.multiple)}),")
    a(")")
    a("")
    a("# §10.3.19-27 use-case features: the slot reads the feature's address;")
    a("# the feature is a R/W register at `alias` in the manufacturer window.")
    a("#   name, slot, alias, reset, allowed, min, max, access")
    a("DEVICE = (")
    for d in m.dev:
        a(f'    ("{d.name}", 0x{d.slot:04X}, 0x{d.alias:X}, 0x{d.reset:X}, {_tup(d.allowed)}, '
          f'{_opt(d.minv)}, {_opt(d.maxv)}, "{"WO" if d.wo else "RW"}"),')
    a(")")
    a("")
    a("# Manufacturer-window words that are not feature aliases:")
    a("#   name, addr, reset, min, max, allowed")
    a("MANUFACTURER = (")
    for w in m.mfr:
        a(f'    ("{w.name}", 0x{m.mfr_base + w.off:X}, 0x{w.reset:X}, {_opt(w.minv)}, '
          f'{_opt(w.maxv)}, {_tup(w.allowed)}),')
    a(")")
    a("")
    a(f"MFR_BASE = 0x{m.mfr_base:X}")
    a(f"MFR_WORDS = {m.mfr_words}")
    a(f"XML_BLOB_ADDR = 0x{m.xml['blob_addr']:08X}")
    a(f"XML_BLOB_BYTES = {m.blob_bytes}")
    a(f"XML_URL = {m.xml_url!r}")
    a("")
    return "\n".join(L)


def _takes(x, feat_names: Dict[str, str]) -> str:
    """What a write may set, and the GenICam feature, for the Markdown view."""
    t = []
    if x.entries:
        t.append(", ".join(f"{k} = 0x{v:X}" for k, v in x.entries.items()))
    elif x.allowed is not None:
        t.append(", ".join(f"0x{v:X}" for v in x.allowed))
    if x.minv is not None or x.maxv is not None:
        t.append(f"{x.minv or 0} .. {'—' if x.maxv is None else x.maxv}")
    if getattr(x, "wo", False):
        t.append("write-only (read 0x44)")
    f = feat_names.get(x.name)
    if f:
        t.append(f"XML `{f}`")
    return "; ".join(t)


def gen_md(m: Map) -> str:
    L = ["# cxp_regmap — register map", "", f"_{BANNER}_", "",
         "The register file is `cxp_ctrl_bootstrap_regs`; the decode order and the",
         "ConnectionReset behaviour are described in its header.", "",
         "## Bootstrap registers (Table 45)", "",
         "| Address | Name | Kind | Size | Power-on | ConnectionReset | Notes |",
         "|---|---|---|---|---|---|---|"]
    a = L.append
    for r in m.rows:
        pon = crs = ""
        notes = []
        if r.kind == "RO":
            pon = f"0x{int(r.value):08X}"
        elif r.kind == "RW":
            pon = f"0x{r.reset:X}"
            crs = "" if r.conn_reset is None else f"0x{r.conn_reset:X}"
            if r.max_links:
                notes.append("writes ≥ p_NUM_LINKS: 0x41")
            elif r.maxv is not None:
                notes.append(f"writes > {r.maxv}: 0x41")
            if r.allowed:
                notes.append("takes " + ", ".join(f"0x{v:X}" for v in r.allowed) + "; others 0x41")
            if r.wr_pulse:
                notes.append(f"write pulses `{r.wr_pulse}`")
        elif r.kind == "STR":
            pon = f'"{r.value}"'
        elif r.kind == "CNT":
            notes.append(f"live `{r.inp}`; write 0 pulses its clear")
        elif r.kind == "CRST":
            notes.append("write 1: §10.3.28 reset; self-clears")
        elif r.kind == "NVSTR":
            notes.append(f"power-on from `{r.nv}`")
        elif r.kind == "ZERO":
            notes.append("reads 0")
        if r.out:
            notes.append(f"→ `{r.out}`")
        a(f"| 0x{r.addr:04X} | {r.name} | {r.kind} | {r.nbytes} | {pon} | {crs} | {'; '.join(notes)} |")
    a("")
    a("## Use-case features (§10.3.19-27)")
    a("")
    a("Each 0x3000 slot reads (only) the address of its feature; the feature is a")
    a("R/W register at that manufacturer address.  A ConnectionReset leaves them alone.")
    a("")
    feat = {x.name: x.gc.get("feature", x.name) for x in (*m.rows, *m.dev, *m.mfr) if x.gc}
    a("| Slot | Feature address | Name | Power-on | Takes | Port |")
    a("|---|---|---|---|---|---|")
    for d in m.dev:
        al = f"0x{d.alias:X}" if d.alias else "—"
        port = f"`{d.out}`" + (f", write pulses `{d.wr_pulse}`" if d.wr_pulse else "")
        pon = f"0x{d.reset:04X} (`{d.reset_param}`)" if d.reset_param else f"{d.reset}"
        a(f"| 0x{d.slot:04X} | {al} | {d.name} | {pon} | {_takes(d, feat)} | {port} |")
    a("")
    a(f"## Manufacturer words (0x{m.mfr_base:X} window)")
    a("")
    a("| Address | Name | Power-on | Takes | Port |")
    a("|---|---|---|---|---|")
    for w in m.mfr:
        a(f"| 0x{m.mfr_base + w.off:X} | {w.name} | {w.reset} | {_takes(w, feat)} | "
          f"{('`' + w.out + '`') if w.out else ''} |")
    a("")
    a("## GenICam XML ROM")
    a("")
    a(f"`{m.xml['file']}`, {m.blob_bytes} bytes (0x{m.blob_bytes:X}) at 0x{m.xml['blob_addr']:08X};")
    a(f"XmlUrl = `{m.xml_url}`.")
    a("")
    return "\n".join(L)


# =============================================================================
# Driver
# =============================================================================
def outputs(m: Map) -> Dict[str, str]:
    return {
        m.xml["file"]: m.xml_bytes.decode("utf-8"),
        OUT_PKG: gen_pkg(m),
        m.xml["mem"]: gen_mem(m),
        OUT_PY: gen_py(m),
        OUT_MODEL: gen_regmodel(m),
        OUT_H: gen_h(m),
        OUT_HPP: gen_hpp(m),
        OUT_MD: gen_md(m),
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if an output is stale")
    args = ap.parse_args()
    m = load()
    stale = 0
    for rel, text in outputs(m).items():
        path = os.path.join(ROOT, rel)
        old = open(path).read() if os.path.exists(path) else None
        if old == text:
            continue
        if args.check:
            stale += 1
            print(f"stale: {rel}")
            sys.stdout.writelines(difflib.unified_diff(
                (old or "").splitlines(True), text.splitlines(True), rel, rel + " (generated)", n=1))
        else:
            with open(path, "w", newline="\n") as f:
                f.write(text)
            print(f"wrote {rel}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
