"""Register map as data for the reference model.  Generated by src/regmap/gen_regmap.py from src/regmap/cxp_regmap.yaml -- do not edit."""

from __future__ import annotations

# One entry per bootstrap row (Table 45), in address order:
#   name, addr, kind, nbytes, value, reset, conn_reset, max,
#   allowed, bits, min, multiple
# `value` is the constant of an RO row or the text of a STR row;
# `conn_reset` is the value §10.3.28 loads, or None to leave it.
BOOTSTRAP = (
    ("Standard", 0x0000, "RO", 4, 0xC0A79AE5, 0x0, None, None, None, 32, None, None),
    ("Revision", 0x0004, "RO", 4, 0x10001, 0x0, None, None, None, 32, None, None),
    ("XmlManifestSize", 0x0008, "RO", 4, 0x1, 0x0, None, None, None, 32, None, None),
    ("XmlManifestSelector", 0x000C, "RW", 4, None, 0x0, 0x0, 0x0, None, 32, None, None),
    ("XmlVersion", 0x0010, "RO", 4, 0x100, 0x0, None, None, None, 32, None, None),
    ("XmlSchemaVersion", 0x0014, "RO", 4, 0x10100, 0x0, None, None, None, 32, None, None),
    ("XmlUrlAddress", 0x0018, "RO", 4, 0x6000, 0x0, None, None, None, 32, None, None),
    ("Iidc2Address", 0x001C, "RO", 4, 0x0, 0x0, None, None, None, 32, None, None),
    ("XmlUrl", 0x6000, "STR", 64, 'Local:cxp_camera.xml;90000000;4357', 0x0, None, None, None, 32, None, None),
    ("DeviceVendorName", 0x2000, "STR", 32, 'AcmeCXP', 0x0, None, None, None, 32, None, None),
    ("DeviceModelName", 0x2020, "STR", 32, 'CamModel', 0x0, None, None, None, 32, None, None),
    ("DeviceManufacturerInfo", 0x2040, "STR", 48, 'AcmeCXP camera', 0x0, None, None, None, 32, None, None),
    ("DeviceVersion", 0x2070, "STR", 32, '1.1.1', 0x0, None, None, None, 32, None, None),
    ("DeviceSerialNumber", 0x20B0, "STR", 16, 'SN-0001', 0x0, None, None, None, 32, None, None),
    ("DeviceUserID", 0x20C0, "NVSTR", 16, None, 0x0, None, None, None, 32, None, None),
    ("ConnectionReset", 0x4000, "CRST", 4, None, 0x0, None, 0x1, None, 32, None, None),
    ("DeviceConnectionID", 0x4004, "RO", 4, 0x0, 0x0, None, None, None, 32, None, None),
    ("MasterHostConnectionID", 0x4008, "RW", 4, None, 0x0, 0x0, None, None, 32, None, None),
    ("ControlPacketSizeMax", 0x400C, "RO", 4, 0x118, 0x0, None, None, None, 32, None, None),
    ("StreamPacketSizeMax", 0x4010, "RW", 4, None, 0x0, 0x0, None, None, 32, None, 0x4),
    ("ConnectionConfig", 0x4014, "RW", 4, None, 0x10028, 0x10028, None, (0x10028,), 32, None, None),
    ("ConnectionConfigDefault", 0x4018, "RO", 4, 0x10028, 0x0, None, None, None, 32, None, None),
    ("TestMode", 0x401C, "RW", 4, None, 0x0, 0x0, 0x1, None, 1, None, None),
    ("TestErrorCountSelector", 0x4020, "RW", 4, None, 0x0, 0x0, 0x0, None, 32, None, None),
    ("TestErrorCount", 0x4024, "CNT", 4, None, 0x0, None, None, None, 32, None, None),
    ("TestPacketCountTx", 0x4028, "CNT", 8, None, 0x0, None, None, None, 32, None, None),
    ("TestPacketCountRx", 0x4030, "CNT", 8, None, 0x0, None, None, None, 32, None, None),
    ("ElectricalComplianceTest", 0x4038, "RW", 4, None, 0x0, 0x0, None, None, 32, None, None),
    ("HsUpconnection", 0x403C, "RO", 4, 0x0, 0x0, None, None, None, 32, None, None),
    ("ImageNStreamIdAddress", 0x3020, "ZERO", 4064, None, 0x0, None, None, None, 32, None, None),
)

# §10.3.19-27 use-case features: the slot reads the feature's address;
# the feature is a R/W register at `alias` in the manufacturer window.
#   name, slot, alias, reset, allowed, min, max, access
DEVICE = (
    ("Width", 0x3000, 0x10000, 0x280, None, 0x1, 0x1000, "RW"),
    ("Height", 0x3004, 0x10004, 0x1E0, None, 0x1, 0x1000, "RW"),
    ("AcquisitionMode", 0x3008, 0x10040, 0x0, (0x0,), None, None, "RW"),
    ("AcquisitionStart", 0x300C, 0x10010, 0x0, None, None, None, "WO"),
    ("AcquisitionStop", 0x3010, 0x10014, 0x0, None, None, None, "WO"),
    ("PixelFormat", 0x3014, 0x10008, 0x1080001, (0x1080001, 0x1100003, 0x1100005, 0x1100025, 0x1100007,), None, None, "RW"),
    ("TapGeometry", 0x3018, 0x10028, 0x0, (0x0,), None, None, "RW"),
    ("Image1StreamID", 0x301C, 0x1002C, 0x1, None, None, 0xFF, "RW"),
)

# Manufacturer-window words that are not feature aliases:
#   name, addr, reset, min, max, allowed
MANUFACTURER = (
    ("MfrReserved1", 0x1000C, 0x0, None, None, None),
    ("FrameCount", 0x10018, 0x0, None, 0xFFFF, None),
    ("TestPattern", 0x1001C, 0x0, None, None, (0x0, 0x1, 0x2, 0x3,)),
    ("OffsetX", 0x10020, 0x0, None, 0xFFF, None),
    ("OffsetY", 0x10024, 0x0, None, 0xFFF, None),
    ("SourceTag", 0x10030, 0x0, None, 0xFFFF, None),
    ("StreamFlags", 0x10034, 0x0, None, 0xFF, None),
    ("TpgRun", 0x10038, 0x1, None, 0x1, None),
    ("MfrReserved2", 0x1003C, 0x0, None, None, None),
)

MFR_BASE = 0x10000
MFR_WORDS = 32
XML_BLOB_ADDR = 0x90000000
XML_BLOB_BYTES = 17239
XML_URL = 'Local:cxp_camera.xml;90000000;4357'
