#!/usr/bin/env python3
"""Fail on a register-map address written out by hand.

    python3 tools/check_regmap_literals.py [dir ...]
        default dirs: src/emu/host src/verif src/tb_unit src/emu/bridge

Every bootstrap, use-case, manufacturer and XML ROM address has a generated
name (cxp_regmap_pkg / cxp_regmap.h / cxp_regmap.hpp / cxp_protocol.regmap).
A number literal in code that equals one of them —

    0x2000..0x20CC (GenICam strings)  0x3000..0x301C (use-case slots)
    0x4000..0x403C (CXP group)  0x6000 (XmlUrl; Table 45 manufacturer space)
    0x10000..0x1007C (manufacturer window)  0x90000000 (XML ROM)

— is a second copy that drifts when the map changes.  Only code is checked:
comments, docstrings and string literals may name an address.  Python is
tokenised; C / C++ / SystemVerilog have their comments and strings removed
first.  Generated files and build trees are skipped.

A real exception goes in ALLOW below, with the reason.
"""

from __future__ import annotations

import io
import os
import re
import sys
import tokenize

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DIRS = ["src/emu/host", "src/verif", "src/tb_unit", "src/emu/bridge"]
EXTS = {".py", ".c", ".h", ".cpp", ".hpp", ".sv", ".svh", ".v"}
SKIP_DIRS = {"build", "__pycache__", "00_test_results", "obj_dir", ".git"}
SKIP_PREFIX = ("sim_build",)

# The address set, from the generated map (not a hand list).
sys.path.insert(0, os.path.join(ROOT, "src", "model", "cxp_protocol"))
from cxp_protocol import regmodel  # noqa: E402

# The Support group (0x0000..0x001C) is left out: its addresses are the
# small numbers every protocol test uses for other things.
ADDRS = set()
for _r in regmodel.BOOTSTRAP:
    if _r[2] != "ZERO" and _r[1] >= 0x2000:
        ADDRS.update(range(_r[1], _r[1] + max(4, _r[3]), 4))
for _d in regmodel.DEVICE:
    ADDRS.update((_d[1], _d[2]))
ADDRS.update(range(regmodel.MFR_BASE, regmodel.MFR_BASE + 4 * regmodel.MFR_WORDS, 4))
ADDRS.add(regmodel.XML_BLOB_ADDR)
ADDRS.add(0x6000)          # Table 45: start of the manufacturer-specific space

# (path relative to the repo, text on the line) -> why it may stay.
ALLOW = {
    # Table 45 itself: the spec's manufacturer-space boundary, one definition.
    ("src/emu/host/src/cxp/validation/context.h",
     "MANUFACTURER_SPACE = 0x6000"): "spec constant (Table 45), not a map address",
    # §10.3.31 ControlPacketSizeMax upper bound: a size, not an address.
    ("src/emu/host/src/cxp/validation/cases/_common.cpp",
     "cpsm <= 0x10000"): "a size limit (§10.3.31), not an address",
}

NUM = re.compile(r"(?<![\w.])(?:0[xX][0-9A-Fa-f_]+|\d+'[hH][0-9A-Fa-f_]+|32'h[0-9A-Fa-f_]+)")


def _value(tok: str):
    t = tok.replace("_", "")
    if "'" in t:
        return int(t.split("'")[1][1:], 16)
    try:
        return int(t, 16) if t[:2] in ("0x", "0X") else None
    except ValueError:
        return None


def _py_numbers(text: str):
    """(line number, token) of every hex number token in Python code."""
    try:
        for tok in tokenize.generate_tokens(io.StringIO(text).readline):
            if tok.type == tokenize.NUMBER and tok.string[:2] in ("0x", "0X"):
                yield tok.start[0], tok.string
    except (tokenize.TokenError, IndentationError, SyntaxError):
        return


_C_STRIP = re.compile(r'//[^\n]*|/\*.*?\*/|"(?:\\.|[^"\\\n])*"', re.S)


def _c_numbers(text: str):
    """(line number, token) of every hex number in C / C++ / SV code."""
    # Blank out comments and strings, keeping the line structure.
    code = _C_STRIP.sub(lambda m: re.sub(r"[^\n]", " ", m.group(0)), text)
    for n, line in enumerate(code.splitlines(), 1):
        for m in NUM.finditer(line):
            yield n, m.group(0)


def _generated(text: str) -> bool:
    return "Generated by src/regmap/gen_regmap.py" in text[:400]


def check(paths) -> int:
    bad = 0
    used = set()
    for base in paths:
        for dp, dns, fns in os.walk(os.path.join(ROOT, base)):
            dns[:] = [d for d in dns if d not in SKIP_DIRS and not d.startswith(SKIP_PREFIX)]
            for fn in sorted(fns):
                if os.path.splitext(fn)[1] not in EXTS:
                    continue
                path = os.path.join(dp, fn)
                rel = os.path.relpath(path, ROOT)
                try:
                    text = open(path, encoding="utf-8", errors="replace").read()
                except OSError:
                    continue
                if _generated(text):
                    continue
                lines = text.splitlines()
                nums = _py_numbers(text) if fn.endswith(".py") else _c_numbers(text)
                for n, tok in nums:
                    v = _value(tok)
                    if v is None or v not in ADDRS:
                        continue
                    line = lines[n - 1] if n <= len(lines) else ""
                    key = next((k for k in ALLOW if k[0] == rel and k[1] in line), None)
                    if key:
                        used.add(key)
                        continue
                    bad += 1
                    print(f"{rel}:{n}: {tok} is a register-map address; use its generated name")
    for k in ALLOW:
        if k not in used and any(k[0].startswith(p) for p in paths):
            print(f"note: allow-list entry not needed any more: {k[0]}: {k[1]!r}")
    print(f"check_regmap_literals: {', '.join(paths)}: {bad} hand-written address(es)")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(check(sys.argv[1:] or DIRS))
