#!/usr/bin/env python3
"""Check the mechanical rules of docs/style/rtl_coding_style.sv on the RTL.

    python3 tools/check_style.py            # every file in src/rtl/cxp_ip.f
    python3 tools/check_style.py FILE...    # just these

Rules (the guide explains each):
  * at most 100 characters per line, no tabs, no trailing blanks
  * `default_nettype none` before the module, `default_nettype wire` after
  * a header block with Description and Versions
  * parameters p_UPPER; ports end in _i / _o, except clocks (*clk) and
    resets (*rst_n)
  * instances are named <module>_i or <module>_<tag>_i
  * no inline lint pragmas (waivers live in src/rtl/cxp_ip.vlt)

Generated files (banner "Generated by ...") are skipped.  EXCEPTIONS lists
the known, documented departures.
"""

from __future__ import annotations

import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RTL = os.path.join(ROOT, "src", "rtl")
MAX_COLS = 100

# (file, rule, name) -> reason
EXCEPTIONS = {
    ("cxp_tx_linktest.sv", "param", "DATA_WORDS"): "read by name from the unit TB",
    ("cxp_tx_linktest.sv", "param", "GAP_WORDS"): "read by name from the unit TB",
}
# cxp_interface_top keeps its un-suffixed ports: every bench and the PyUVM
# harness connect to them by name.
PORT_EXEMPT_FILES = {"cxp_interface_top.sv"}

RE_PARAM = re.compile(r"^\s*parameter\s+(?:[\w:]+\s+)?(?:\[[^\]]*\]\s*)*(\w+)\s*=")
RE_PORT = re.compile(r"^\s*(input|output|inout)\s+(?:wire\s+|var\s+)?(?:logic\s+|[\w:]+\s+)?"
                     r"(?:\[[^\]]*\]\s*)*(\w+)")
RE_INST_HEAD = re.compile(r"^\s*(cxp_\w+)\s*(#\s*\()?\s*$")


def rtl_files():
    out = []
    with open(os.path.join(RTL, "cxp_ip.f")) as f:
        for ln in f:
            ln = ln.split("//")[0].strip()
            if ln:
                out.append(os.path.join(RTL, ln))
    return out


def check(path: str):
    name = os.path.basename(path)
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if "Generated by" in text[:2000]:
        return []
    errs = []
    lines = text.split("\n")

    def err(i, msg):
        errs.append(f"{name}:{i}: {msg}")

    for i, ln in enumerate(lines, 1):
        if len(ln) > MAX_COLS:
            err(i, f"line is {len(ln)} characters (max {MAX_COLS})")
        if "\t" in ln:
            err(i, "tab character")
        if ln != ln.rstrip():
            err(i, "trailing blank")
        if re.search(r"(verilator|spyglass|synopsys)\s+lint_(off|on)", ln):
            err(i, "inline lint pragma (waive in src/rtl/cxp_ip.vlt)")

    is_pkg = re.search(r"^\s*package\s+\w+", text, re.M) is not None
    if not is_pkg:
        if "`default_nettype none" not in text:
            err(1, "missing `default_nettype none")
        if "`default_nettype wire" not in text:
            err(len(lines), "missing `default_nettype wire at the end")
    if "Description:" not in text[:4000] or "Versions:" not in text[:6000]:
        err(1, "header block needs Description: and Versions:")

    # Module header: parameters and ports
    m = re.search(r"^\s*module\s+(\w+)", text, re.M)
    if m:
        hdr_end = text.index(");", m.end())
        start_line = text[:m.start()].count("\n") + 1
        for j, ln in enumerate(text[m.start():hdr_end].split("\n")):
            code = ln.split("//")[0]
            pm = RE_PARAM.match(code)
            if pm:
                p = pm.group(1)
                if not re.fullmatch(r"p_[A-Z0-9_]+", p) and (name, "param", p) not in EXCEPTIONS:
                    err(start_line + j, f"parameter {p}: name it p_UPPER")
            pt = RE_PORT.match(code)
            if pt and name not in PORT_EXEMPT_FILES:
                d, p = pt.group(1), pt.group(2)
                if re.search(r"clk$|rst_n$", p):
                    continue
                want = "_i" if d == "input" else "_o"
                if not p.endswith(want):
                    err(start_line + j, f"port {p}: {d} ports end in {want}")

    # Instance names
    pending = None
    for i, ln in enumerate(lines, 1):
        code = ln.split("//")[0]
        h = RE_INST_HEAD.match(code)
        if h and "module" not in code:
            pending = h.group(1)
            continue
        im = re.match(r"^\s*(?:\)\s*)?(\w+)\s*\(\s*$", code)
        direct = (re.match(r"^\s*(cxp_\w+)\s+(\w+)\s*\(\s*$", code)
                  or re.match(r"^\s*(cxp_\w+)\s*#\s*\(.*\)\s*(\w+)\s*\(\s*$", code))
        if direct:
            mod, inst = direct.group(1), direct.group(2)
        elif pending and im and code.strip().startswith(")"):
            mod, inst = pending, im.group(1)
        else:
            continue
        pending = None
        if not re.fullmatch(rf"{mod}(_\w+)?_i", inst):
            err(i, f"instance {inst} of {mod}: name it {mod}_i or {mod}_<tag>_i")
    return errs


def main(argv):
    files = argv[1:] or rtl_files()
    errs = []
    for f in files:
        errs += check(f)
    for e in errs:
        print(e)
    print(f"check_style: {len(files)} files, {len(errs)} findings")
    return 1 if errs else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
